import XCTest

/// Launch screenshot tests generated by Xcode.
///
/// These tests launch the app and save a screenshot attachment for each UI configuration
/// that Xcode chooses to run.
final class Medicine_Date_AlerterUITestsLaunchTests: XCTestCase {

    /// Tells XCTest to repeat this launch test for each target UI configuration.
    override class var runsForEachTargetApplicationUIConfiguration: Bool {
        true
    }

    /// Runs before the launch screenshot test.
    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    /// Launches the app and stores a screenshot in the test report.
    @MainActor
    func testLaunch() throws {
        let app = XCUIApplication()
        app.launch()

        let attachment = XCTAttachment(screenshot: app.screenshot())
        attachment.name = "Launch Screen"
        attachment.lifetime = .keepAlways
        add(attachment)
    }
}
